name: Tests + Coverage + SonarCloud

on:
  push:
    branches: [ "sre-analysis" ]
  pull_request:
    branches: [ "sre-analysis" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # safest for deps

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          # test & demo deps used by this project
          pip install pytest pytest-cov pytest-django freezegun factory_boy djangorestframework
          pip install django-user-accounts pinax-templates pinax-theme-bootstrap pinax-invitations

      - name: Run tests with coverage (creates coverage.xml)
        env:
          DJANGO_SETTINGS_MODULE: demodesk.config.settings
        run: |
          pytest -q --ds=demodesk.config.settings \
            --cov=helpdesk --cov-branch --cov-report=xml:coverage.xml

      - name: Upload coverage.xml (for your records)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=helpdesk_sre
            -Dsonar.organization=<YOUR_SONARCLOUD_ORG>
            -Dsonar.sources=src/helpdesk
            -Dsonar.tests=tests
            -Dsonar.inclusions=src/helpdesk/**/*.py
            -Dsonar.exclusions=**/migrations/**,demodesk/**,docs/**,standalone/**,src/helpdesk/static/**,**/*.html
            -Dsonar.test.inclusions=tests/**/*.py
            -Dsonar.python.coverage.reportPaths=coverage.xml
